### ISSUE TITLE
sh:node makes the documentation generator crash

### ISSUE THREAD

**Issue by psiotwo** [sparna-git/shacl-play#103]
On some inputs I get a NPE - difficult to reproduce, as it does not seem to be deterministic. But seems to be connected with (complex) `sh:node`s, e.g.
```
sh:node [
      a sh:NodeShape ;
      sh:property [
          sh:path skos:inScheme ;
          sh:hasValue <http://eurovoc.europa.eu/100141> ;
        ] ;
    ] ;
sh:nodeKind sh:IRI ;
```

**Comment by tfrancart** [comment]
Could be related to using blank nodes. Would you mind attaching a SHACL file that triggers the error ?
I think sh:node is expected to contain an IRI of a NodeShape, as described at https://shacl-play.sparna.fr/play/doc#propertyShape

**Comment by tfrancart** [comment]
This has been fixed - but potentially we will see the blank node identifier in the document, if the anonymous node shape does not have an rdfs:label.
