### ISSUE TITLE
Error in diagram generation

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/shacl-play#106]
With this file

[solidar-shapes.zip](https://github.com/sparna-git/shacl-play/files/12793453/solidar-shapes.zip)

we get an error in diagram generation:

![image](https://github.com/sparna-git/shacl-play/assets/2728945/4315f67a-76fd-4c98-9c73-ccd4717bae03)

@JAs2701 could you have a look ? Thanks

**Comment by JAs2701** [comment]
fixed problem with diamond generate

![solidar-shapes_0](https://github.com/sparna-git/shacl-play/assets/67315354/e617b472-2fda-489b-9b48-b7eaf4d285ee)
