### ISSUE TITLE
further improvements to SHACL diagram

### ISSUE THREAD

**Issue by VladimirAlexiev** [sparna-git/shacl-play#116]
Thanks for fixing https://github.com/sparna-git/shacl-play/issues/94 !
* We'll explore adding such diagrams to SHACL generated from our Semantic Objects (SOML).
* You can compare to diagrams generated from SOML, eg see https://bsdd.ontotext.com/:
  * PlantUML Overview Diagram: [png](https://bsdd.ontotext.com/img/bsdd-graphql-soml-diagram-overview.png) or [svg](http://www.plantuml.com/plantuml/svg/jP91Qzmm48Nl_XN2nq9CDj3BKa8WEVPG0ksfO6QbyLhiI39ZcIN_lbQrZZBnuhQK-3IUUP_UF5iFOmIEawEgjmOLkY6-A8VkW3pcbhQi2Il2BgeO5DjZ7vMnZ3hQuAlnPFq034xvO734GNs-hIfDC8wg_hAFRC4V9m9kUIBa_Rtwxcsi5Oo_Yw8yKZXWUxQnRnsoDJCtpkgl2OSZ9kBrfL08F0EG20r9_nWc7_aboPUwg0yXd9Be6Jjaz1gVWfuS-hpFgbj0WWFI33u51zOdzQKiaiuIjbqWWvpMI6tRMGtHXWp8LW7FoREVcMyS1kIOTrzUYewiFxrHFIELizytLvGq5wmShK_emJda5hnfNrULZ5ZywaZ-WxSnVW1Dc43PgVBdLTUUUjSqkrhTc9kvlcsQJxKqbTHUQJ7ywPN9lsu3sh2GkOJ5--5i9GQRbjccMEx-a6e0HX-b91dsbipZtxlUDStTxCeowFe-N5mPwUAKIpIL-1JgOpxZS2bNPjjH5hK8eVuvIdbIbFlbT75XfMolW2YSqUJBl17wlyvzG6ycHxy0)
  * PlantUML Full Diagram: [png](https://bsdd.ontotext.com/img/bsdd-graphql-soml-diagram.png) or [svg](http://www.plantuml.com/plantuml/svg/xLdVJnj747xtNt6YBstLe92sBoX2YO1Ag4b82RGlbQovtJ6UiZ-kitCELjt_lLulHrcudbUqYK754kYy_hwTdRcPRsVlNWK1bjQQqPGqLcWRcLSMROqSqf0YLWP71YTIYQ-OpgTIQM9KGjwDmWMv1XXivRp6W4tr_VFHI1a8eTfwkNjkV8tZZoJJiKKcJU32xbxr1jnv2-UuLK6u_bBzCNhvXJ2uq02ZaszkVjbRlDmrv2vsznOLwUKVqwBQsTxUMOoMluI66CpOUS46TCGui5XzMGUjT-FbLuig29Cx7oHHyCfhBC560tU0VzxmlFR-8hfwWXDaT0eFl6ejEea-tntztCuhCEWqS8Hh44p_JybYkTT3G24nW_51O9cE8MQ5WXYeVTywuNaCJtUz-Opupz91c6AQ6-0njmPvwV2PevGCyUBHkZe037DRU_CtzFcTg1YeqIn3SU0ja5i58rq-X70qyvNOlVD22czvqSynLqgsxpMkgJa3GSwQM7FwJ5HXzHbIw4BXMXBsZ4qHt7h68pVnfNW7TfsBZ0OXu46cBeEJ1W5fGv7z6N8WxuPAxcCKsEaokzwpRv0bIKltPPE22qfe1aBUnU0Kt__o4bNUELI2klCsoyWOrw__YPcKztXop7HERkszo3XdeT088uZdDrcv51ZI870wRp9mttw6hmS2F6W09-GeyihMWmsZMjavl6mCE2YdOb1CJJcUBBhGZzvvyUrt6UQrZNVaUFAXhOE0Y-f5JeOOXmQLCAdzbcF-hyM_GNSkq_MmrfBpRJXo4WTalfRn5a9O2pgT8bklvmuigLEq3J98oxYUI3Q1XcDzrPDrJLfXSgRbl0S6Yu9yi_H2KLdW9TZ6z5chmHWluzfVfbvQJL4bSGe7oUoYghqt2Ew6Bc3SliQXyHUenn04cSAAPU7oy5APDj0COoegic2YkGBYaUiX3kmhA5ElZoTl4KBB6CFQ-LTaaDmzLqfkUANtRsiQ444kAzjcEW-amFpKWXEIUGyf7XHMqAjy-HbCYp-Iqulg_TsX0LkCZG65-hZ-3PMKfrtYBL73n7nhdr5OewvTyNNOTsqyLQRgAsy2XXlCjjQKPW_bku_WfVpWsO8KtSAMT1dEaQm9smovC6eTj3zeNMioez22ES66CQ2JrUvpnfJwbPvsUq86nnDlD78ySCLXcf2AlDHyvqCFlqNgQaTbwqujmdxFsFFxzrQRxv0UTzDp_usrM9YvcxQueMGq8AYF9kfm9S_lm0xUdm6jlQ_KFZgbBK_YC7VUpMsEBLVP1oQUYNUz9v-WkTRDVF3JA2UZkHQoN3pxrvdBNxRQdfyslEOfM8iy1gV7wTH-nu4kmZqEFFuJ_GPsdQTp-TEv_EbSle5Z-I3h17zlYL5VqygC_S8aK1lCQKyF0HxuGu1X4kDAzL2lJl-5d9JQ7r0-xuE6f-QtyELNyGE9dV_50ucKaddwnGul7zdyoy0LV9RNON5NT-zkemjzy2nvtBj0NhqixVjinVLjLS_qi-LrlFbRUTkSitPlFKBvrLLwDVTeWBJrOdlxnT84PoRwZXR91AEvchmxU0_EdcQyTc1dZGCf7VPlkw6cP7G-sc-rC6nTPdPXw_qnsirDPhJgqvZiX7t8MFf4OtkTiRpMRaKrDXqVh_QWWNbxSk7keJXz2dEXO__xLRz2frjh_W80)

Here are some more ideas for improvement (based on the euBusinessGraph diagram):
- At the documentation page you have "Diagrams" in plural: do you use sh:group or some other mechanism to decide how many diagrams to make, and which shapes to include?
- this expresses "there are 2 fixed values of rdf:type":
```
rdf:type [2..2] = org:Site
rdf:type = locn:Address
```
but I find it a bit confusing visually. I think this is better:
```
rdf:type [2..2] = org:Site, locn:Address
```
But if there are many types, that could get too long... So maybe as a compromise:
```
rdf:type [2..2] = org:Site
rdf:type [2..2] = locn:Address
```
- there are many fields without a type annotation, eg `locn:fullAddress [0..1]`.
But on the doc page it shows that you recognize the two types: `locn:fullAddress : xsd:string or rdf:langString`.
So could you depict this as `locn:fullAddress : xsd:string, rdf:langString [0..1]` ?
- Could you add `IRI` as "type annotation"? Eg I wondered what these two are, until I remembered (one points to Concept of a particular ConceptScheme but I don't remember why I didn't try to reflect this; the other is a "free" IRI like `<mailto:someone@example.com>`). So they should become
```
rov:orgType : IRI [0..1]
schema:email : IRI
```

@tfrancart **thanks for your excellent work** and have a great holiday season!!

**Comment by tfrancart** [comment]
Hello @VladimirAlexiev and thank you for your very encouraging and positive comment

> At the documentation page you have "Diagrams" in plural: do you use sh:group or some other mechanism to decide how many diagrams to make, and which shapes to include?

See https://shacl-play.sparna.fr/play/draw#custom-nodeShapes. We use a `foaf:depiction` property on NodeShapes to give the URI of a diagram, with its title + description, in which we want the NodeShape to be included. See [this complete example illustrating an output](https://shacl-play.sparna.fr/play/doc?format=html&url=https%3A%2F%2Fgist.githubusercontent.com%2Ftfrancart%2Fd61ad4f81a08e0fa2d40910d990e2e72%2Fraw%2F450872672903795bac80194352de5c3b0aa727a4%2Fannotate-shacl.ttl&includeDiagram=true), generated from [this SHACL file](https://gist.github.com/tfrancart/d61ad4f81a08e0fa2d40910d990e2e72) (diagrams resources are at the end of the file). Also illustrates how to play with colors.

> this expresses "there are 2 fixed values of rdf:type": (...)

I find your SHACL a bit strange. You have 2 property shapes for rdf:type :

```
ebgsh:Address  a        sh:NodeShape ;
        sh:property     [ sh:hasValue  org:Site ;
                          sh:maxCount  2 ;
                          sh:minCount  2 ;
                          sh:path      rdf:type
                        ] ;
        sh:property     [ sh:hasValue  locn:Address ;
                          sh:path      rdf:type
                        ] ;
```

I would have expected the following, with a single property shape using `sh:in`

```
ebgsh:Address  a        sh:NodeShape ;
        sh:property     [ 
                          sh:in  (org:Site, locn:Address) ;
                          sh:maxCount  2 ;
                          sh:minCount  2 ;
                          sh:path      rdf:type
                        ] ;
```

> there are many fields without a type annotation, eg locn:fullAddress [0..1].
> But on the doc page it shows that you recognize the two types: locn:fullAddress : xsd:string or rdf:langString.
> So could you depict this as locn:fullAddress : xsd:string, rdf:langString [0..1] ?

Indeed the HTML table documentation generation is currently smarter than the diagrams with respect to `sh:or`. I will see how to improve this;

> Could you add IRI as "type annotation"? Eg I wondered what these two are, until I remembered (one points to Concept of a 
> particular ConceptScheme but I don't remember why I didn't try to reflect this; the other is a "free" IRI like 
> <mailto:someone@example.com>). So they should become
> rov:orgType : IRI [0..1]
> schema:email : IRI

Yes, I think we wanted to keep the boxes in the diagram compact and readable. We'll see if/how this can be improved.

Thank you for your constructive comments, and stay tuned for more fun with SHACL :-)
