### ISSUE TITLE
DatatypeProperty of range rdf:langString not handled

### ISSUE THREAD

**Issue by nchauvat** [sparna-git/shacl-play#133]
Hi Thomas,

Thank you for shacl-play.

Using it to generate shapes from an ontology with a DatatypeProperty of range rdf:langString, such as

```
my:title a owl:DatatypeProperty ;
    rdfs:domain my:ClassyClass ;
    rdfs:range rdf:langString.
```

we got

```
sh:class rdf:langString
```

instead of the expected

```
sh:datatype rdf:langString
```

see https://www.w3.org/TR/rdf12-concepts/#section-Graph-Literal about rdf:langString.

After changing sh:class to sh:datatype, the data is correctly validated by shacl-play.

**Comment by tfrancart** [comment]
Hello @nchauvat and thanks for stopping by.
Indeed I think the problem is [here](https://github.com/sparna-git/owl2shacl/blob/main/owl2sh-open.ttl#L295)
