### ISSUE TITLE
sh:ignoredProperties should be a list

### ISSUE THREAD

**Issue by nchauvat** [sparna-git/shacl-play#142]
Hi Thomas,

Here is a description of what I would think is a bug in the generation of shacl shapes from OWL.

To reproduce:
```
java -jar shacl-play-app-0.7.0-onejar.jar owl2shacl -i skos.owl -o skos_closed_schacl.ttl -s CLOSED
```

Running this shacl on SKOS data will generate violations for triples "my:thesaurus_term rdf:type skos:Concept".

If you change skos_closed_shacl.ttl to replace
```
sh:ignoredProperties rdf:type ;
```
with
```
sh:ignoredProperties ( rdf:type  ) ;
```
and run the validation again, the above violation disappears.

What do you tihnk ?

**Comment by nchauvat** [comment]
According to https://www.w3.org/TR/shacl/#ClosedConstraintComponent the value of sh:ignoredProperties has to be a SHACL List.

**Comment by tfrancart** [comment]
I think you are absolutely right. Lists are complicated to generate in SPARQL (can't remember the details). There is some code to post process the result of the SPARQL query : https://github.com/sparna-git/shacl-play/blob/master/shacl-play/src/main/java/fr/sparna/rdf/shacl/shaclplay/convert/ConvertController.java#L257
