### ISSUE TITLE
Ability to control the colors of lines in the documentation table

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/shacl-play#172]
RUIM : we need to flag/color certain properties that are actually instantiated in the actual version of the RUIM.
Use shacl-play:color and shacl-play:backgroundColor, as with NodeShape

**Comment by JAs2701** [comment]
![{EC7315AD-6C3F-4A7A-8272-B77232913AF8}](https://github.com/user-attachments/assets/b45b8b90-1f54-42ea-a703-4a6280fb4405)

**Comment by tfrancart** [comment]
Merci @JAs2701 pour la couleur de police du texte, il faudrait que cela change la couleur sur **toute la ligne**, pas seulement le libellé de la première colonne
