### ISSUE TITLE
[Draw] Also display cardinalities for the same namespace

### ISSUE THREAD

**Issue by JohannesLipp** [sparna-git/shacl-play#32]
Expected behavior: When declaring minCount and maxCount, they are included as cardinalities in the output PNG, despite of their namespaces.

Actual behavior: These cardinalities are only displayed for external namespaces (i.e., via [1..2] at the edges to those classes), but not for the same namespace (i.e., they are simply listed without cardinalities in the same box). 
Can you please fix/add this? Thank you so much!

Cardinalities are note displayed for the same namespace:
SHACL input (with minCount and maxCount):
![image](https://user-images.githubusercontent.com/15930331/125630638-a39fd1a8-ea70-460f-ad50-0f9c1333a397.png)

PNG output (no cardinalities displayed):
![image](https://user-images.githubusercontent.com/15930331/125630726-eb4078d5-1897-422c-a36b-f83be6aab8f5.png)

When using other namespaces, the cardinalities are displayed at the edges towards those classes:
![image](https://user-images.githubusercontent.com/15930331/125630372-abf1fd14-ca60-41e8-b766-44e4cf4b16d9.png)

**Comment by tfrancart** [comment]
Could you post here a minimal SHACL file to reproduce the behavior ? I cannot reproduce the problem - see for example the included shape i nthe catalog "OpenArchaeo Shapes".
Thanks, this would be helpful

**Comment by tfrancart** [comment]
This could be because your prefix contains an hyphen. Can you try with a prefix "gaxcor" instead of "gax-core" ?

**Comment by JAs2701** [comment]
Hello @JohannesLipp , We tried with the following SHACL file and cannot reproduce the issue. Can you provide a test file that demonstrates the behavior you see ? Thank you

SHACL input
```
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix gax-core: <http://www.w3.org/2001/XMLSchema#> .
@prefix gax-asset: <http://www.w3.org/2001/XMLSchema#> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix dct: <http://purl.org/dc/terms/> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

gax-asset:MinimumAssetShape a sh:NodeShape ;
sh:targetClass gax-asset:Asset ;
sh:property [sh:path gax-core:hasName ;
	sh:minCount 1 ;
	sh:maxCount 1 ;
	sh:datatype xsd:string ] ;
sh:property [sh:path dct:description ;
	sh:minCount 1 ;
	sh:maxCount 1 ;
	sh:datatype rdfs:Literal ] ;
sh:property [sh:path gax-core:ownedBy ;
	sh:minCount 1;
	sh:datatype foaf:Person ] ;
.
```

PNG output 
![Demo-Shacl_cardinalities](https://user-images.githubusercontent.com/67315354/125919642-0a3c7b02-6573-45a6-aa3c-e6f5a13961da.png)

Best Regard

**Comment by moosmannp** [comment]
Hello, @tfrancart and @JAs2701,
thanks for your quick responses. I'm a collegue of @JohannesLipp and just tried to reproduce the stated behaviour. When using the [web application](https://shacl-play.sparna.fr/play/draw) we get the correct output, yet when creating the .png file using the command line, the cardinalities are not shown. Maybe we are missing something in the command? This is the command line we use: 
java -jar shacl-play-app-0.4-onejar.jar draw -i shapeFile.ttl -o shapeFile.png

**Comment by tfrancart** [comment]
Hi, yes the release is not in synch with the web application, I will fix that

**Comment by tfrancart** [comment]
Ne release 0.5 has been published, can you try it and close the ticket if it fixes the issue ? Thanks

**Comment by JohannesLipp** [comment]
Thank you so much! @moosmannp could you please verify the new release? Thank you!

**Comment by moosmannp** [comment]
@tfrancart Thanks a lot! Works fine now! @JohannesLipp Please close the ticket, thanks.
