### ISSUE TITLE
Documentation generation: 0..* cardinalities  appear as blank spaces 

### ISSUE THREAD

**Issue by NatasaSofou** [sparna-git/shacl-play#52]
In SHACL  if  `sh:minCount `and `sh:maxCount `are not defined, the cardinality is `0..n` by default. When using the https://shacl-play.sparna.fr/play/doc ,  in the documentation generated, the cardinality is displayed as empty for this default case. However, this was taken into consideration by the previous versions of the generator ( a few days ago) and it was properly illustrated as  `0..*` in the produced html.

**Comment by tfrancart** [comment]
Should be fixed now in the online app, thanks for reporting.
