### ISSUE TITLE
Afficher une ancre au survol de la souris devant chaque titre de section pour les pages de documentation

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/shacl-play#55]
Pour la doc de la doc : https://shacl-play.sparna.fr/play/doc
Pour la doc de la génération SPARQL : https://shacl-play.sparna.fr/play/sparql

Fonctionnement identiquer à https://docs.sparnatural.eu/, utiliser la même librairie Javascript

**Comment by andrea-perego** [comment]
In the documentation generated by https://shacl-play.sparna.fr/play/doc the anchor char (`#`) is not shown unless you click on it. See, e.g.:

https://shacl-play.sparna.fr/play/doc?url=https%3A%2F%2Feuroparl.github.io%2Feli-ep%2Feli-ep.shacl.ttl&includeDiagram=true
