### ISSUE TITLE
Logo insertion does not work

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/shacl-play#63]

**Comment by andrea-perego** [comment]
It still does not work when using the Web form at https://shacl-play.sparna.fr/play/doc . See, e.g.:

https://shacl-play.sparna.fr/play/doc?url=https%3A%2F%2Feuroparl.github.io%2Feli-ep%2Feli-ep.shacl.ttl&includeDiagram=true

It works with the API and/or when manually adding the `inputLogo` param to the URL query string.

**Comment by tfrancart** [comment]
This works for me:

![image](https://user-images.githubusercontent.com/2728945/187649915-6ebcd511-f05f-4be8-be14-1422aedbabf0.png)

and then:

![image](https://user-images.githubusercontent.com/2728945/187650035-6da5a2c7-eb80-4d6f-a685-1e38095f576d.png)


Can you be more precise on what you use and what you do in the web form for cases where it does not work ?

**Comment by andrea-perego** [comment]
The problem is with the English version of the Web form. 

BTW, this is how the relevant fields look like:

![shacl-play-doc-web-form](https://user-images.githubusercontent.com/9863263/187656525-4c25093c-9dd5-4d34-94f8-a1ac2160dcd7.png)

**Comment by tfrancart** [comment]
Apart from the obvious translation issue in the english version of the form, the logo insertion works for me:

![image](https://user-images.githubusercontent.com/2728945/187657923-954952a1-c5dc-4a42-9b23-62582114fa98.png)

Which URL do you use ?
Which browser do you use ?

**Comment by andrea-perego** [comment]
The logo is indeed included when specifying the SHACL file in the "Upload" field, as in your example. But not when using the "URL" field:

![shacl-play-doc-web-form-2](https://user-images.githubusercontent.com/9863263/187659589-f0d84b0c-b7bd-43ee-a734-483972f1d444.png)

The result:

![shacl-play-doc-web-form-2-output](https://user-images.githubusercontent.com/9863263/187659859-12a0182c-f654-4563-b437-03ca21c496eb.png)

Chrome and Firefox give the same output.

**Comment by tfrancart** [comment]
I see now. Thanks

**Comment by tfrancart** [comment]
Fixed in the online version, not in releases
