### ISSUE TITLE
Click on UML diagram does not navigate to corresponding section of Docs

### ISSUE THREAD

**Issue by nikokaoja** [sparna-git/shacl-play#66]
In previous versions of `shacl-play` (0.6), when UML diagram is generated as a part of docs it was possible to navigate to sections of docs by clicking on objects on UML diagram. 

In the latest version (0.6.1), when clicking on UML diagram, the page navigates to part of the diagram instead of the corresponding doc section.

**Comment by tfrancart** [comment]
I think the update of plantuml in this new version now inserts IDs inside the SVG diagram with exactly the same name as our section anchors...

**Comment by nikokaoja** [comment]
What would be solution? To drop version of plantuml dependency ?

**Comment by nikokaoja** [comment]
Just to confirm that after doing `regex` update on SVG IDs clicking on UML diagrams works as before.

**Comment by tfrancart** [comment]
Fixed in the online version, not in releases
