### ISSUE TITLE
HTML TITLE element missing from documentation

### ISSUE THREAD

**Issue by andrea-perego** [sparna-git/shacl-play#67]
See, e.g.:

https://shacl-play.sparna.fr/play/doc?url=https%3A%2F%2Feuroparl.github.io%2Feli-ep%2Feli-ep.shacl.ttl&includeDiagram=true

**Comment by tfrancart** [comment]
Yes, we have recommendation from EP designers to modify the HTML structure, HTML title is part of this work

**Comment by tfrancart** [comment]
Fixed in online version
