### ISSUE TITLE
Suggestion Doc Generator: Consider reading label and description from SKOS metadata if RDFS metadata not found

### ISSUE THREAD

**Issue by oising** [sparna-git/shacl-play#99]
Right now you're only looking for rdfs:label ("property name") and rdfs:comments ("description") when filling out the following table in the documentation generator:

![image](https://github.com/sparna-git/shacl-play/assets/1844001/e970aa42-5542-46c5-813f-8e5721a798d2)

Consider also looking for skos:prefLabel and skos:definition respectively if the rdfs equivalents are not found.

**Comment by tfrancart** [comment]
Done. SKOS prefLabel/definition are read first, and if not found, rdfs:label/comment.
sh:name/description always have precedence.

Let me know how it works for you. Test especially sorting.
